#!/usr/bin/env bash
# Script: 5-is_the_host_on_the_network
# Description: Ping an IP address and display the results

# Check if an argument is provided
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 {IP_ADDRESS}"
    exit 1
fi

# Extract the IP address from the command-line argument
ip_address="$1"

# Ping the IP address 5 times
ping -c 5 "$ip_address"
