#!/usr/bin/env bash

# Function to clean up and exit the script
terminator() {
  rm /var/run/myscript.pid  # Remove the PID file
  exit  # Exit the script
}

# Save the current process ID (PID) to a PID file
echo "$$" > /var/run/myscript.pid

# Infinite loop to print the message every 2 seconds
while true
do
  echo "To infinity and beyond"

  # Sleep for 2 seconds
  sleep 2

  # Set up a trap to handle SIGINT (Ctrl+C) signal
  trap 'echo "Y U no love me?!"' SIGINT

  # Set up a trap to handle SIGTERM signal and call the terminator function
  trap 'echo "I hate the kill command" && terminator' SIGTERM

  # Set up a trap to call the terminator function on SIGQUIT signal
  trap 'terminator' SIGQUIT
done

# End of the script
