#!/usr/bin/env bash
# This script displays "Best School" 10 times, but for the 9th iteration, it says "Hi" on a new line

# Initializing a counter
counter=0

# Using a while loop to display "Best School" 10 times
while [ $counter -lt 10 ]; do
    # Using an if statement to check if it's the 9th iteration
    if [ $counter -eq 8 ]; then
        echo "Hi"
    else
        echo "Best School"
    fi

    # Incrementing the counter
    ((counter++))
done
