#!/usr/bin/env bash
# Script: 0-change_your_home_IP
# Description: Configure localhost and facebook.com IP addresses

# Backup /etc/hosts file
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
